# Generated by Django 3.1.5 on 2021-12-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transcriptModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoID', models.CharField(max_length=100)),
                ('transcript', models.TextField()),
            ],
        ),
    ]
